package com.demo.onetoonehibernate.OneToOneHibernate.model;
// Generated 20 Feb, 2018 10:14:12 AM by Hibernate Tools 5.2.8.Final

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private Integer id;
	private String name;
	private Pancard pancard;

	public Person() {
	}

	public Person(String name) {
		this.name = name;
	}

	public Person(String name, Pancard pancard) {
		this.name = name;
		this.pancard = pancard;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Pancard getPancard() {
		return this.pancard;
	}

	public void setPancard(Pancard pancard) {
		this.pancard = pancard;
	}

}
